apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-weaviate-pvc
  labels:
    app: weaviate
  namespace: sage
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi