apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sage

namePrefix: dev-
commonLabels:
  env: dev

resources:
- ../base
# - ingress.yaml

patches:
  - path: gpus.yaml
    target:
      kind: Deployment
      labelSelector: "app in (reranker-transformers, multi2vec-bind)"

images:
  - name: semitechnologies/multi2vec-bind
    newTag: imagebind-latest
  - name: semitechnologies/reranker-transformers
    newTag: cross-encoder-ms-marco-MiniLM-L-6-v2-latest
  - name: semitechnologies/weaviate
    newTag: 1.31.0