apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/triton:latest
          env:
            - name: PYTORCH_CUDA_ALLOC_CONF
              value: "expandable_segments:True,max_split_size_mb:256"
            - name: TRANSFORMERS_VERBOSITY
              value: "info"
            - name: TORCHDYNAMO_DISABLE
              value: "1"
            - name: MODEL_REPOSITORY
              value: "/app/models"
            - name: CLIP_MODEL_PATH
              value: "/models/DFN5B-CLIP-ViT-H-14-378"
            - name: CLIP_MODEL_VERSION
              value: "419d1f8f6a96aabaf5913c526d059facda50c24b"
            - name: GEMMA_MODEL_PATH
              value: "/models/gemma-3-4b-it"
            - name: GEMMA_MODEL_VERSION
              value: "093f9f388b31de276ce2de164bdc2081324b9767"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
          resources:
            limits:
              cpu: 1
              memory: 8Gi
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi
            requests:
              cpu: 1
              memory: 8Gi
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi
          ports:
          - name: http
            containerPort: 8000
          - name: grpc
            containerPort: 8001
          - name: metrics
            containerPort: 8002
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /models/gemma-3-4b-it
            name: models
          - mountPath: /models/DFN5B-CLIP-ViT-H-14-378
            name: models
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      - name: models
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: triton
  labels:
    app: triton
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
  selector:
    app: triton