apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      initContainers:
        - name: init
          image: python:3.11-slim
          command: ["/bin/bash","-c"]
          args:
            - |
              set -euo pipefail
              /bin/bash /scripts/init-dataset.sh
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
            - name: init-dataset-script
              mountPath: /scripts
            - name: huggingface-cache
              mountPath: "/hf_cache"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
          resources:
            limits:
              cpu: 8
              memory: 16Gi
            requests:
              cpu: 8
              memory: 16Gi
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.32.0
          env:
            - name: RERANKER_INFERENCE_API
              value: "http://$(RERANKER_SERVICE):8080"
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: ENABLE_MODULES
              value: "reranker-transformers,backup-filesystem"
            - name: BACKUP_FILESYSTEM_PATH
              value: "/tmp/backups"
            - name: CLUSTER_HOSTNAME
              value: "node1"
            - name: ASYNC_INDEXING
              value: "true"
            - name: USE_BLOCKMAX_WAND
              value: "true"
            - name: USE_INVERTED_SEARCHABLE
              value: "true"
            - name: PROMETHEUS_MONITORING_ENABLED
              value: "true"
            - name: PROMETHEUS_MONITORING_PORT
              value: "2112"
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
            - name: metrics
              containerPort: 2112
          resources:
            limits:
              cpu: 2
              memory: 3Gi
            requests:
              cpu: 2
              memory: 3Gi
          volumeMounts:
          - name: weaviate-data
            mountPath: /var/lib/weaviate
      restartPolicy: Always
      volumes:
        - name: init-dataset-script
          configMap:
            name: init-dataset-script-cm
        - name: weaviate-data
          emptyDir: {}
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  selector:
    app: weaviate
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
    - port: 2112
      targetPort: 2112
      name: metrics
  type: ClusterIP
