apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.31.0
          env:
            - name: BIND_INFERENCE_API
              value: "http://$(MULTI2VEC_SERVICE):8080"
            - name: RERANKER_INFERENCE_API
              value: "http://$(RERANKER_SERVICE):8080"
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "multi2vec-bind"
            - name: ENABLE_MODULES
              value: "multi2vec-bind,reranker-transformers"
            - name: CLUSTER_HOSTNAME
              value: "node1"
            - name: ASYNC_INDEXING
              value: "true"
            - name: USE_BLOCKMAX_WAND
              value: "true"
            - name: USE_INVERTED_SEARCHABLE
              value: "true"
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  selector:
    app: weaviate
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
  type: ClusterIP
