name: "florence2base_postprocessing"
backend: "python"
max_batch_size: 0
input [
  {
    name: "generated_ids"
    data_type: TYPE_INT64
    dims: [1, 512]
  },
  {
    name: "image_width"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "image_height"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "answer"
    data_type: TYPE_STRING
    dims: [1]
  }
]