name: Push to NRP GitLab Registry for Hybrid Search

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'HybridSearch_example/**'
      - '.github/workflows/nrp-gitlab-registry.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'HybridSearch_example/**'
      - '.github/workflows/nrp-gitlab-registry.yml'

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    env:
      HYBRID_SEARCH_TRITON_IMG: /ndp/sage/hybrid-search/triton
      HYBRID_SEARCH_GRADIO_IMG: /ndp/sage/hybrid-search/gradio-ui
      HYBRID_SEARCH_WEAVMANAGE_IMG: /ndp/sage/hybrid-search/weavmanage
      HYBRID_SEARCH_WEAVLOADER_IMG: /ndp/sage/hybrid-search/weavloader
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAG_NAME=${GITHUB_REF#refs/tags/}

          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            IMAGE_TAG=${BRANCH_NAME}
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            IMAGE_TAG=${TAG_NAME}
          elif [[ "$GITHUB_REF" == refs/pull/* ]]; then
            PR_NUMBER=$(echo "$GITHUB_REF" | cut -d'/' -f3)
            IMAGE_TAG=pr-${PR_NUMBER}
          fi

          IMAGE_TAG=$(echo "$IMAGE_TAG" | tr '/' '-')  # Replace slashes with dashes for branch names
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to NRP GitLab Container Registry
        run: echo "${{ secrets.NRP_GITLAB_PAT }}" | docker login ${{ secrets.NRP_GITLAB_REGISTRY_URL }} -u ${{ secrets.NRP_GITLAB_USERNAME }} --password-stdin

      - name: Build Docker Image for Hybrid Search - Triton
        run: |
          docker build -t ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_TRITON_IMG }}:${{ env.IMAGE_TAG }} HybridSearch_example/triton
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker tag ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_TRITON_IMG }}:${{ env.IMAGE_TAG }} ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_TRITON_IMG }}:latest
          fi

      - name: Build Docker Image for Hybrid Search - Gradio UI
        run: |
          docker build -t ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_GRADIO_IMG }}:${{ env.IMAGE_TAG }} HybridSearch_example/app
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker tag ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_GRADIO_IMG }}:${{ env.IMAGE_TAG }} ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_GRADIO_IMG }}:latest
          fi

      - name: Build Docker Image for Hybrid Search - Weaviate Manager
        run: |
          docker build -t ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVMANAGE_IMG }}:${{ env.IMAGE_TAG }} HybridSearch_example/weavmanage
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker tag ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVMANAGE_IMG }}:${{ env.IMAGE_TAG }} ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVMANAGE_IMG }}:latest
          fi

      - name: Build Docker Image for Hybrid Search - Weaviate Loader
        run: |
          docker build -t ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVLOADER_IMG }}:${{ env.IMAGE_TAG }} HybridSearch_example/weavloader
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker tag ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVLOADER_IMG }}:${{ env.IMAGE_TAG }} ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVLOADER_IMG }}:latest
          fi

      - name: Push Docker Image to GitLab Registry for Hybrid Search - Triton
        run: |
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_TRITON_IMG }}:${{ env.IMAGE_TAG }}
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_TRITON_IMG }}:latest
          fi

      - name: Push Docker Image to GitLab Registry for Hybrid Search - Gradio UI
        run: |
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_GRADIO_IMG }}:${{ env.IMAGE_TAG }}
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_GRADIO_IMG }}:latest
          fi

      - name: Push Docker Image to GitLab Registry for Hybrid Search - Weaviate Manager
        run: |
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVMANAGE_IMG }}:${{ env.IMAGE_TAG }}
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVMANAGE_IMG }}:latest
          fi

      - name: Push Docker Image to GitLab Registry for Hybrid Search - Weaviate Loader
        run: |
          docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVLOADER_IMG }}:${{ env.IMAGE_TAG }}
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            docker push ${{ secrets.NRP_GITLAB_REGISTRY_URL }}{{ env.HYBRID_SEARCH_WEAVLOADER_IMG }}:latest
          fi
